name: Test Workflow

on:
  pull_request_target:
    types: [opened]

jobs:
  set-reno-condition:
    runs-on: ubuntu-latest
    outputs:
      generate-release-note: ${{ steps.set-output.outputs.generate-release-note }}
    steps:
      - name: Set generate-release-note output
        id: set-output
        run: |
          labels=$(jq -r '.pull_request.labels[].name' <<<"$GITHUB_EVENT")
          if echo "$labels" | grep -q "ignore-for-release-notes"; then
            echo "::set-output name=generate-release-note::false"
          else
            echo "::set-output name=generate-release-note::true"
          fi
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}

  create-pr-release-note:
    runs-on: ubuntu-latest
    needs: set-reno-condition
    steps:
      # intentionally doing this step first to speed up PR text generation and improve UX
      - name: Generate PR description for this PR and update the PR web page
        uses: vblagoje/pr-auto@v1
        id: pr-auto-step
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Update PR description
        uses: vblagoje/update-pr@v1
        with:
          pr-body: ${{steps.pr-auto-step.outputs.pr-text}}

      # now checkout the repo to add the release note commit to it (if needed)
      - name: Checkout Repository (even forks) to add reno note commit to it
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Generate Release Note for this PR
        uses: vblagoje/reno-auto@v1
        if: needs.set-reno-condition.outputs.generate-release-note == 'true'
        id: reno-auto-step
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Create PR release note and commit it to the branch
        uses: vblagoje/create-or-update-release-note@v2
        if: needs.set-reno-condition.outputs.generate-release-note == 'true'
        with:
          note-name: ${{steps.reno-auto-step.outputs.file-name}}
          note-content: ${{steps.reno-auto-step.outputs.note}}