name: Test Workflow

on:
  pull_request:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  test-pr-update-on-opened-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

      - name: Update PR description
        uses: vblagoje/update-pr@v1
        with:
          pr-body: Let's merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}

  create-pr-release-note:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Generate Release Notes
        uses: vblagoje/auto-reno@main
        id: auto-reno

  find-pr-release-note-on-opened-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

      - name: Find PR release note
        uses: vblagoje/find-pr-release-note@main
        id: find-pr-release-note

      - name: Echo PR release note
        run: echo "I found this release note ${{ steps.find-release-note-id.outputs.note-name }}"

      - name: Echo PR release note without hash
        run: echo "I found this release note ${{ steps.find-release-note-id.outputs.note-name-without-hash }}"
