name: Test Workflow

on:
  pull_request_target:
    types: [opened]

jobs:
  create-pr-release-note:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Generate PR description
        uses: vblagoje/pr-auto@main
        id: pr-auto-step
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Update PR description
        uses: vblagoje/update-pr@main
        with:
          pr-body: ${{steps.pr-auto-step.outputs.pr-text}}

      - name: Generate Release Note for this PR
        uses: vblagoje/reno-auto@main
        id: reno-auto-step
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Create PR release note
        uses: vblagoje/create-or-update-release-note@main
        with:
          note-name: ${{steps.reno-auto-step.outputs.file-name}}
          note-content: ${{steps.reno-auto-step.outputs.note}}