name: Test Workflow

on:
  pull_request:
    types: [opened]

jobs:
  create-pr-release-note:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Generate PR description
        uses: vblagoje/pr-auto@v1
        id: pr-auto-id
        with:
          generation_model: gpt-3.5-turbo
          function_calling_model: gpt-3.5-turbo
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Update PR description
        uses: vblagoje/update-pr@v1
        with:
          pr-body: ${{steps.pr-auto-id.outputs.pr-text}}

      - name: Generate Release Note for this PR
        uses: vblagoje/reno-auto@v1
        id: reno-auto-id
        with:
          generation_model: gpt-3.5-turbo
          function_calling_model: gpt-3.5-turbo
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Create PR release note
        uses: vblagoje/create-or-update-release-note@v1
        with:
          note-name: ${{steps.reno-auto-id.outputs.file-name}}
          note-content: ${{steps.reno-auto-id.outputs.note}}
