name: Test Workflow

on:
  pull_request:
    types: [opened]

jobs:
  create-pr-release-note:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Generate PR description
        uses: vblagoje/auto-pr@main
        id: auto-pr
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: https://api.fireworks.ai/inference/v1
          generation_model: accounts/fireworks/models/mixtral-8x7b-instruct
          function_calling_model: accounts/fireworks/models/fw-function-call-34b-v0

      - name: Update PR description
        uses: vblagoje/update-pr@main
        with:
          pr-body: ${{steps.auto-pr.outputs.pr-text}}

      - name: Generate Release Note for this PR
        uses: vblagoje/auto-reno@main
        id: auto-reno
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: https://api.fireworks.ai/inference/v1
          generation_model: accounts/fireworks/models/mixtral-8x7b-instruct
          function_calling_model: accounts/fireworks/models/fw-function-call-34b-v0

      - name: Create PR release note
        uses: vblagoje/create-or-update-release-note@main
        with:
          note-name: ${{steps.auto-reno.outputs.file-name}}
          note-content: ${{steps.auto-reno.outputs.note}}
