name: Workflow test playground

on:
  pull_request:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  test-pr-update-on-opened-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

      - name: Update PR description
        uses: vblagoje/update-pr@v1
        with:
          pr-body: Let's merge ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}

  find-pr-release-note-on-opened-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

      - name: Find PR release note
        uses: vblagoje/find-pr-release-note@main
        id: find-release-note-id

      - name: Echo PR release note
        run: echo "I found this release note ${{ steps.find-release-note-id.outputs.note-name }}"
      - name: Echo PR relase note without hash
        run: echo "I found this release note ${{ steps.find-release-note-id.outputs.note-name-without-hash }}"
